### ISSUE TITLE
Span in Japanese Text

### ISSUE THREAD

**Issue by yucca-t-k** [pubannotation/textae#117]
When I tried to select a span for denotation annotation, entire sentence (line?) is always selected and I cannot select a part (e.g. word) of a sentence

**Comment by jdkim** [comment]
That is because of the boundary detection function of TextAE. If you turn the function off (press the 'b' key), you will be able to select any span as you like. Please close this issue after you see it works fine.

**Comment by yucca-t-k** [comment]
Worked fine but I would rather have boundary detection off by default for Japanese text.
